### PR TITLE
Gradle

### PR DESCRIPTION
**Pull request by elect86**
Hi dear,

I implemented gradle, it allows to download and get it running with one click

Ps: may I ask if you could move it under [java-opengl-labs](https://github.com/java-opengl-labs)? :)

### CODE REVIEW

**Comment by xranby** [comment]
Thank you elect86 for your contribution now merged into
https://github.com/xranby/jogamp-forum-examples/commits/master

I have merged your changes and improved it:
* i have removed all native jogamp binarys from your commit
* i changed gradle to download the jogamp natives from maven
* i added gradle support to run the demo from command line
   
You can fork it under java-opengl-labs if you prefer.

You can now test this demo by running:

    git clone https://github.com/xranby/jogamp-forum-examples/
    cd jogamp-forum-examples
    ./gradlew run
    
    ./gradlew -PmainClass=xranby.com.gudinna.JogAmpGraphAPITextDemo run
    ./gradlew -PmainClass=xranby.com.gudinna.JogAmpGraphAPINurbsDemo run
    ./gradlew -PmainClass=elect.ogldevtutorials.tutorial04.Tutorial04 run
    ./gradlew -PmainClass=Lili.justTexture.justTexture run

**Comment by elect86** [comment]
don't remove the natives, otherwise it won't work on linux (from the IDE?)

**Comment by xranby** [comment]
All examples work on Linux after my changes
The examples also work fine from inside IDE

The important part was to use jogl-all-main instead of jogl-all if you want gradle to download the natives
Also i fetched fonts-p0 from jogl required by the graph text demo

    dependencies {
    
        def jogl = '2.3.2'
    
        compile "org.jogamp.gluegen:gluegen-rt-main:$jogl"
        compile "org.jogamp.jogl:jogl-all-main:$jogl"
        compile "org.jogamp.jogl:jogl:$jogl:fonts-p0@jar"
    }

**Comment by xranby** [comment]
I have verified running the examples on Linux from inside the following IDE

Eclipse neon.2
Eclipse neon.2 with exported "runable jar"
IntelliJ idea 171.3566.24
NetBeans 8.1 with gradle plugin

everything looks ok!

**Comment by elect86** [comment]
I isolated the problem, the crash happens when I have these lines

```        Display display = NewtFactory.createDisplay(null);
        Screen screen = NewtFactory.createScreen(display, 0);
        GLProfile glProfile = GLProfile.get(GLProfile.GL3);
        GLCapabilities glCapabilities = new GLCapabilities(glProfile);

        window = GLWindow.create(screen, glCapabilities);
```

Instead 

```        GLProfile gLProfile = GLProfile.getDefault();

        GLCapabilities gLCapabilities = new GLCapabilities(gLProfile);

        glWindow = GLWindow.create(gLCapabilities);
```

> Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/elect/IdeaProjects/jogamp-forum-examples/natives/linux-amd64//libnativewindow_awt.so

**Pull request closed without merging**
